### PR TITLE
added new tasks

### PR DESCRIPTION
**Pull request by Menalque**
I added new tasks for myself for next week.

### CODE REVIEW

**Comment by gitonthescene** [comment]
Nice!  Will have a look shortly.

**Comment by gitonthescene** [comment]
I think there are some issues here.  First I think you accidentally added a “p” before one of the headings.  But also it looks like it doesn’t have the changes from the merge we did on Sunday.  I’ll see if I can figure out what happened.

**Comment by gitonthescene** [comment]
The only think I can think that happened is that you made your changes to an old copy you had around and then committed that rather than starting with an up-to-date copy.

I’m going to reject this pull request.

You can delete the commit from your repository and make the changes again.  This uses the somewhat sophisticated “git rebase” command.

Alternatively you can fetch the version in my repository, copy that on top of your edits and then reapply your edits on top of that.

Do you want to try to figure that out?  I can try to walk you through it.

**Comment by gitonthescene** [comment]
There’s also a lesson here to “look before you leap”.  It’s generally a good idea to run “git diff” before git adding a file for a commit.  If it’s not what you want you can fix it before you commit.

Generally it’s less of a hassle to catch problems earlt.

**Comment by Menalque** [comment]
My first pull request... rejected! 

I'll take a look and let you know if I have questions.

**Comment by Menalque** [comment]
When I opened glenn-meetup.org this morning on Emacs, I didn't notice that the updated file on my harddrive was called glenn-meetup.org~ with the tilde on the end, and without the ~ was the old file.

**Comment by gitonthescene** [comment]
With emacs, the [~ files](https://www.gnu.org/software/emacs/manual/html_node/emacs/Backup-Names.html) are the backup files.  I’m not sure if this matches what you saw.

There are also temporary files which are created as part of emacs’ [auto save](https://www.gnu.org/software/emacs/manual/html_node/emacs/Auto-Save.html#Auto-Save) feature.  They look like `.#filename`.  These files save the file to disc periodically just in case emacs crashes.  This is different from the actual file which saves only what you want when you actually save it.

Neither of these files should be committed to git and both are different from the main file.

**Pull request closed without merging**
